# reference points
reference_point:
  filepath_1: /wps/berlin_5.csv
  filepath_2: /wps/berlin_5.csv
  distance: 1.8


# name of topic to subscribe and publish
topic:
  scan: /scan
  odom: /odom
  nav: /drive


# configuration values for driving algorithm
driving:
  speed_max: 6.5
  speed_min: 2.1
  robot_scale: 0.3
  threshold: 2.0
  gap_size: 1
  filter_scale: 1.08
  gap_theta_gain: 40.0
  ref_theta_gain: 1.0
